services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27069:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P4ssw0rd
      MONGO_INITDB_DATABASE: notes
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5469:5432
    environment:
      - POSTGRES_USER=notes
      - POSTGRES_PASSWORD=P4ssw0rd
      - POSTGRES_DB=notes
    volumes:
      - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
      - postgres_data:/var/lib/postgresql/data
      
volumes:
  mongo_data:
  postgres_data:
      
